// What a browser pays to open the shell, and what it can put off.
//
// A report, not a gate: nothing here fails a build. The number that matters is the entry chunk,
// because everything in it is parsed and evaluated before the first frame, and the shell's two
// lazy() calls already keep Monaco and XTerm out of it. The trap this is here to catch is a
// value import that drags a library into the entry by accident: `sideEffects: false` lets rollup
// drop a whole unused module, but once one binding is used the module is kept, and a top-level
// `z.object(...)` is an opaque call it will not shake out. That is how a type guard and eight
// constants once cost 95 KB of zod.
//
// `--why` answers "what is in there" by walking the entry chunk's sourcemap and attributing each
// generated byte span to the source that produced it.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const shell = new URL("..", import.meta.url).pathname;
const dist = join(shell, "dist");

const kb = (n: number) => `${(n / 1024).toFixed(1)} KB`;
const pad = (s: string | number, w: number) => String(s).padStart(w);

/** the entry js and css, as index.html asks for them */
function entryFiles(root: string): { js: string; css: string } {
  const text = readFileSync(join(root, "index.html"), "utf8");
  const js = text.match(/src="\/assets\/([^"]+\.js)"/)?.[1];
  const css = text.match(/href="\/assets\/([^"]+\.css)"/)?.[1];
  if (!js || !css) throw new Error(`no entry js/css in ${root}/index.html; run: bun run build`);
  return { js, css };
}

function report(root: string) {
  const { js, css } = entryFiles(root);
  const jsBytes = statSync(join(root, "assets", js)).size;
  const cssBytes = statSync(join(root, "assets", css)).size;
  const gz = (p: string) => Bun.gzipSync(new Uint8Array(readFileSync(p))).length;
  const jsGz = gz(join(root, "assets", js));
  const cssGz = gz(join(root, "assets", css));

  let lazyBytes = 0;
  let lazyCount = 0;
  for (const f of readdirSync(join(root, "assets"))) {
    // --why builds with sourcemaps; they ship to nobody, so they are not payload
    if (f === js || f === css || f.endsWith(".map")) continue;
    lazyBytes += statSync(join(root, "assets", f)).size;
    lazyCount++;
  }

  console.log("eager, every load:");
  console.log(`  ${pad(jsBytes, 9)}  gzip ${pad(jsGz, 8)}  ${js}`);
  console.log(`  ${pad(cssBytes, 9)}  gzip ${pad(cssGz, 8)}  ${css}`);
  console.log(`  ${pad(jsBytes + cssBytes, 9)}  gzip ${pad(jsGz + cssGz, 8)}  total (${kb(jsBytes + cssBytes)})`);
  console.log(`lazy, on demand:`);
  console.log(`  ${pad(lazyBytes, 9)}  across ${lazyCount} files (${kb(lazyBytes)})`);
}

/** base64 VLQ, one field at a time */
function decodeVlq(s: string): number[] {
  const B = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const out: number[] = [];
  let shift = 0;
  let value = 0;
  for (const c of s) {
    const d = B.indexOf(c);
    if (d < 0) continue;
    value += (d & 31) << shift;
    if (d & 32) {
      shift += 5;
      continue;
    }
    out.push(value & 1 ? -(value >> 1) : value >> 1);
    value = 0;
    shift = 0;
  }
  return out;
}

/** which bucket a source path is reported under: the npm package, or the shell surface */
function bucket(src: string): string {
  if (src.includes("node_modules")) {
    const p = src.split("node_modules/").pop() ?? src;
    const parts = p.split("/");
    return `npm: ${parts[0]?.startsWith("@") ? `${parts[0]}/${parts[1]}` : parts[0]}`;
  }
  if (src.includes("packages/shared/")) return "@toyon/shared";
  const i = src.indexOf("src/");
  if (i >= 0) {
    const parts = src.slice(i + 4).split("/");
    return `shell/src/${parts.length > 2 ? `${parts[0]}/${parts[1]}` : parts.join("/")}`;
  }
  return src.replace(/^(\.\.\/)+/, "");
}

/** a source-mapped build, so the entry chunk's bytes can be traced back to what wrote them */
function why() {
  const out = mkdtempSync(join(tmpdir(), "toyon-size-"));
  try {
    console.log("building with sourcemaps (this takes a few seconds)...\n");
    execFileSync("bun", ["run", "vite", "build", "--sourcemap", "--outDir", out, "--emptyOutDir"], {
      cwd: shell,
      stdio: "pipe",
    });
    report(out);

    const { js } = entryFiles(out);
    const code = readFileSync(join(out, "assets", js), "utf8");
    const map = JSON.parse(readFileSync(join(out, "assets", `${js}.map`), "utf8"));
    const lines = code.split("\n");

    // a segment owns the generated bytes from its column up to the next segment's, or to the end
    // of the line. Segments with only a generated column carry no source and are skipped.
    const bySource = new Map<number, number>();
    let srcIdx = 0;
    map.mappings.split(";").forEach((line: string, li: number) => {
      let genCol = 0;
      const segs: Array<{ col: number; src: number | null }> = [];
      for (const s of line.split(",")) {
        if (!s) continue;
        const f = decodeVlq(s);
        genCol += f[0] ?? 0;
        if (f.length >= 4) {
          srcIdx += f[1] ?? 0;
          segs.push({ col: genCol, src: srcIdx });
        } else {
          segs.push({ col: genCol, src: null });
        }
      }
      const width = lines[li]?.length ?? 0;
      segs.forEach((seg, i) => {
        if (seg.src === null) return;
        const end = i + 1 < segs.length ? (segs[i + 1]?.col ?? width) : width;
        bySource.set(seg.src, (bySource.get(seg.src) ?? 0) + Math.max(0, end - seg.col));
      });
    });

    const agg = new Map<string, number>();
    let total = 0;
    for (const [i, n] of bySource) {
      const b = bucket(map.sources[i] ?? `#${i}`);
      agg.set(b, (agg.get(b) ?? 0) + n);
      total += n;
    }

    console.log(`\nwhat is in the entry chunk (${total} bytes mapped):`);
    for (const [name, n] of [...agg].sort((a, b) => b[1] - a[1]).slice(0, 25)) {
      console.log(`  ${pad(n, 8)}  ${pad(((n / total) * 100).toFixed(1), 5)}%  ${name}`);
    }
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
}

if (process.argv.includes("--why")) why();
else report(dist);
