#!/usr/bin/env bash
# One-file "control plane" for the cloud spike: one Fly app + one volume + one
# machine per invocation. No accounts, no billing, no database.
#
#   provision.sh up <app-name>       create app, volume, secrets; build + deploy; print URL
#   provision.sh url <app-name>      print the shell URL again (reads the token secret file)
#   provision.sh destroy <app-name>  delete the app and its volume so nothing keeps billing
#
# Needs: flyctl (https://fly.io/docs/flyctl/install/), `fly auth login`, and an
# Anthropic API key for `up`: either ANTHROPIC_API_KEY in the environment or the
# file ~/.orchardist/cloud/anthropic.key (mode 600). No local Docker: the image is
# built remotely. Region, VM size and proxy port range are knobs below.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
REGION="${FLY_REGION:-sjc}"
VM_SIZE="${FLY_VM_SIZE:-shared-cpu-2x}"
VM_MEM="${FLY_VM_MEMORY:-2048}"
VOL_GB="${FLY_VOLUME_GB:-5}"
PROXY_FROM=10001
PROXY_TO=10008
DAEMON_PORT=4141

cmd="${1:-}"; app="${2:-}"
[ -n "$cmd" ] && [ -n "$app" ] || { sed -n '2,12p' "$0"; exit 1; }
command -v fly >/dev/null || { echo "flyctl not found; install it and run: fly auth login" >&2; exit 1; }

state_dir="$HOME/.orchardist/cloud"
token_file="$state_dir/$app.token"

write_fly_toml() {
  local f="$HERE/fly.toml"
  {
    cat <<TOML
# generated by provision.sh — do not edit, regenerate
app = "$app"
primary_region = "$REGION"

[env]
  ORCHARDIST_CLOUD = "1"
  ORCHARDIST_PORT = "$DAEMON_PORT"
  ORCHARDIST_HOME = "/data/orchardist"
  ORCHARDIST_PROXY_PORTS = "$PROXY_FROM-$PROXY_TO"
  ORCHARDIST_PUBLIC_HOST = "$app.fly.dev"

[mounts]
  source = "orch_data"
  destination = "/data"

[[vm]]
  size = "$VM_SIZE"
  memory = "${VM_MEM}mb"

# shell + daemon websocket
[[services]]
  internal_port = $DAEMON_PORT
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [[services.http_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"
    method = "get"
    path = "/health"
TOML
    # one public TLS port per worktree preview proxy; Fly terminates TLS on any port
    for p in $(seq "$PROXY_FROM" "$PROXY_TO"); do
      cat <<TOML

[[services]]
  internal_port = $p
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    port = $p
    handlers = ["tls", "http"]
TOML
    done
  } > "$f"
  echo "wrote $f"
}

case "$cmd" in
  up)
    mkdir -p "$state_dir"; chmod 700 "$state_dir"
    # bring-your-own-key: env var, else a file you wrote yourself (never pasted into a chat/log)
    key_file="$state_dir/anthropic.key"
    if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -f "$key_file" ]; then
      ANTHROPIC_API_KEY="$(tr -d '[:space:]' < "$key_file")"
    fi
    : "${ANTHROPIC_API_KEY:?put your Anthropic API key in $key_file (chmod 600) or export ANTHROPIC_API_KEY}"
    if [ ! -f "$token_file" ]; then
      openssl rand -hex 32 > "$token_file"; chmod 600 "$token_file"
    fi
    token="$(cat "$token_file")"
    write_fly_toml
    fly apps list --json 2>/dev/null | grep -q "\"Name\": *\"$app\"" || fly apps create "$app"
    fly volumes list -a "$app" --json 2>/dev/null | grep -q '"orch_data"' \
      || fly volumes create orch_data -a "$app" --region "$REGION" --size "$VOL_GB" --yes
    fly secrets set -a "$app" --stage \
      ORCHARDIST_TOKEN="$token" \
      ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
      ${DEMO_REPO_URL:+DEMO_REPO_URL="$DEMO_REPO_URL"}
    fly deploy "$ROOT" --config "$HERE/fly.toml" --dockerfile "$HERE/Dockerfile" \
      --remote-only --ha=false --yes
    # public IPs are not always auto-allocated for a config-driven first deploy
    fly ips list -a "$app" 2>/dev/null | grep -q 'v4' || fly ips allocate-v4 --shared -a "$app"
    fly ips list -a "$app" 2>/dev/null | grep -q 'v6' || fly ips allocate-v6 -a "$app"
    echo "waiting for /health…"
    for i in $(seq 1 60); do
      if curl -fsS "https://$app.fly.dev/health" >/dev/null 2>&1; then break; fi
      sleep 2
    done
    echo
    echo "shell:  https://$app.fly.dev/#token=$token"
    echo "logs:   fly logs -a $app"
    echo "stop:   fly machine stop -a $app   (then time the next /health for cold start)"
    ;;
  url)
    [ -f "$token_file" ] || { echo "no token for $app; run: $0 up $app" >&2; exit 1; }
    echo "https://$app.fly.dev/#token=$(cat "$token_file")"
    ;;
  destroy)
    fly apps destroy "$app" --yes   # volumes go with the app
    rm -f "$token_file"
    echo "destroyed $app"
    ;;
  *)
    sed -n '2,12p' "$0"; exit 1 ;;
esac
